# إعدادات النشر في نتفلاي
[build]
  command = "npm run build"
  publish = "dist"

# إعادة توجيه كل الطلبات إلى index.html
# حتى تعمل روابط React Router بشكل صحيح
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
