[build]
  # أمر البناء القياسي لمشاريع Vite
  command = "npm run build" 

  # مجلد النشر القياسي الذي ينتجه أمر 'vite build'
  publish = "dist"

[[redirects]]
  # هذه القاعدة ضرورية لـ React (تطبيقات الصفحة الواحدة)
  # توجه كل المسارات إلى index.html
  from = "/*"
  to = "/index.html"
  status = 200
